# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  webapplication2:
    container_name: webapplication2
    image: webapplication2
    hostname: webapplication2
    build:
      context: .
      dockerfile: WebApplication2/Dockerfile
    ports:
      - 8010:8080
    environment:
      - SOMESERVICE_URL=http://host.docker.internal:8020
      - ZIPKIN_URL=http://host.docker.internal:9411
    depends_on: 
      - rabbitmq
      - zipkin

  someservice:
    container_name: someservice
    image: someservice
    hostname: someservice
    build:
      context: .
      dockerfile: SomeService/Dockerfile
    ports:
      - 8020:8080
    environment:
      - WEBAPPLICATION2_URL=http://host.docker.internal:8010
      - ZIPKIN_URL=http://host.docker.internal:9411
    depends_on: 
      - rabbitmq
      - zipkin

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_ERLANG_COOKIE=SomeRandomStringHere

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411