# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: test
registry: localhost:5000

services:
  - name: web
    project: WebApplication2/WebApplication2.csproj
    bindings:
    - name: http
      protocol: http
      port: 5010
    - name: https
      protocol: https
      port: 5011

  - name: worker
    project: Worker/Worker.csproj
    bindings:
    - name: http
      protocol: http
      port: 5020
    - name: https
      protocol: https
      port: 5021

- name: mssql
  image: mcr.microsoft.com/azure-sql-edge:latest
  env:
  - name: MSSQL_SA_PASSWORD
    value: P@ssw0rd
  - name: MSSQL_PID
    value: Developer
  - name: ACCEPT_EULA
    value: "Y"
  bindings:
  - port: 1433
    connectionString: Server=${host},${port};User Id=sa;Password=${env:MSSQL_SA_PASSWORD};Encrypt=false;Database=AppDb
  volumes:
  - source: .data/sql-edge
    target: /var/opt/mssql/data

  - name: zipkin
    image: openzipkin/zipkin
    bindings:
      - port: 9411

  - name: rabbitmq
    image: rabbitmq:3-management
    bindings:
      - name: rabbit
        port: 5672
        protocol: rabbitmq
      - name: management
        port: 15672