apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      hostname: mssql
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 1433
        env:
          - name: MSSQL_SA_PASSWORD
            value: P@ssw0rd
          - name: MSSQL_PID
            value: Developer
          - name: ACCEPT_EULA
            value: "1"
        volumeMounts:
          - name: sqldata
            mountPath: /var/opt/mssql/data
      initContainers:
      - name: volume-permissions
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c", "chmod -R 777 /var/opt/mssql/data && chown -R 1000:1000 /var/opt/mssql/data"]
        volumeMounts:
        - name: sqldata
          mountPath: /var/opt/mssql/data
      volumes:
        - name: sqldata
          hostPath:
            path: "/host/sql-edge/data"
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-svc
spec:
  type: NodePort
  selector:
    app: mssql # label of the pod
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30037