apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: full-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: worker
  template:
    metadata:
      labels:
        app: full-app
        service: worker
    spec:
      containers:
      - name: worker
        image: sundis/worker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: WEBAPPLICATION2_URL
            value: http://webapplication2:8080/
          - name: RABBITMQ_HOST
            value: rabbitmq-svc
          - name: ZIPKIN_URL
            value: http://zipkin-svc:9411
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: full-app
    service: worker
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: worker